### PR TITLE
Fix lint

### LINKED ISSUE #15: Fix lint
Fix all the linter errors

### PR DESCRIPTION
**Pull request by dianabit**
Fixed linting and added lint script back to build and prepare scripts.
Fixes #15

### CODE REVIEW

File: .eslintignore [hunk 1]
```diff
@@ -1,2 +1,2 @@
-./node_modules
-./dist
```
Comment (chic-geek) [inline .eslintignore:2]: Shouldn't these still be in the file as we wouldn't want to lint files we have no control over?

File: .eslintignore [hunk 2]
```diff
@@ -1,2 +1,2 @@
...
+dist/**
+build/**
```
Comment (chic-geek) [inline .eslintignore:2]: If the linting happens on the uncompiled scripts/styles, then we shouldn't need to do it on the compiled files either?

File: src/App.jsx [hunk 3]
```diff
@@ -1,6 +1,6 @@
 import React from 'react';
-import RichTextEditor from './RichTextEditor';
-import './index.scss';
+import RichTextEditor from './components/RichTextEditor';
+import './components/App/component.scss';
```
Comment (chic-geek) [inline src/App.jsx:3]: We don't need to bring this in because it will be brought in via the `index.js` of the component.

File: src/components/RichTextEditor/utils.jsx [hunk 4]
```diff
@@ -111,7 +110,7 @@ export const rules = [
           case 'paragraphRight':
             return <div className="rte-paragraph-right">{children}</div>;
           case 'link':
-            return <a href="">{children}</a>;
+            return <a href={children}>{children}</a>;
```
Comment (chic-geek) [inline src/components/RichTextEditor/utils.jsx:113]: Will this not try to insert a component into the `href`?

File: .eslintignore (hunk 1 above)
Comment (dianabit) [reply .eslintignore:2]: `node_modules` is ignored by default and `./dist` is not correct, it should be `dist/**,` like below.

File: .eslintignore (hunk 2 above)
Comment (dianabit) [reply .eslintignore:2]: Sorry, I am not sure I understand this one. These two lines make sure linting is not happening in the files within the `dist` and `build` folders (compiled filed).

Comment (chic-geek) [reply .eslintignore:2]: You're right, i read it as a eslint file, not an ignore file. My mistake, ignore me here.

File: src/App.jsx (hunk 3 above)
Comment (chic-geek) [inline src/App.jsx:3]:
```suggestion
```

Comment (chic-geek) [reply src/App.jsx:3]: We don't need this, it's in the `src/components/App/index.js` file already. That way styling is kept local to the component.

File: src/components/RichTextEditor/components/EditorToolbar.jsx [hunk 5]
```diff
@@ -221,7 +221,6 @@ const EditorToolbar = React.forwardRef((props, ref) => {
               <span className="rte-format-toolbar_category-key">ctrl+V</span>
               {' '}
               or
-              {' '}
```
Comment (chic-geek) [inline src/components/RichTextEditor/components/EditorToolbar.jsx:224]: I would keep this in otherwise it'll bunch up the text against the background colour.

Comment (dianabit) [reply src/components/RichTextEditor/components/EditorToolbar.jsx:224]: Good spot. It was just a conflict mix up.
